version: '2'

networks:
  nuccfabric:

volumes:
  orderer.nucc.com:
  peer0.org1.nucc.com:
  peer1.org1.nucc.com:

services:

  orderer.nucc.com:
    extends:
      file:   docker-compose-order.yaml
      service: orderer.nucc.com
    networks:
      - nuccfabric

  peer0.org1.nucc.com:
    extends:
      file:   docker-compose-org1-peer0.yaml
      service: peer0.org1.nucc.com
    networks:
      - nuccfabric
    depends_on:
      - orderer.nucc.com

  cli:
    extends:
      file:   docker-compose-cli.yaml
      service: cli
    networks:
      - nuccfabric

    depends_on:
      - orderer.nucc.com
      - peer0.org1.nucc.com